De warp net review
IEM-Computer-Vision/ICCV19-Paper-Review pull request #56
Opened 2020-01-21 13:20 UTC by Rajatava

2020-01-21 16:32 UTC, shivishbrahma requested changes
Check this one and request again

2020-01-21 16:32 UTC, shivishbrahma commented on DewarpNet_Single_Image_Document_Unwarping_With_Stacked_3D_and_2D_Regression_Networks.md
>  <p allign = "Center">
Make this `<p align="center">`

2020-01-21 16:33 UTC, shivishbrahma commented
@Rajatava all is good but plz change

2020-01-22 04:07 UTC, ucalyptus commented on DewarpNet_Single_Image_Document_Unwarping_With_Stacked_3D_and_2D_Regression_Networks.md
> +<p allign = "Centre">
it should be `center` with a small c

2020-01-22 04:07 UTC, ucalyptus commented on DewarpNet_Single_Image_Document_Unwarping_With_Stacked_3D_and_2D_Regression_Networks.md
> +<p allign = "Centre">
`center`

2020-01-22 04:08 UTC, ucalyptus requested changes
spelling wrong . `center` hobe

2020-01-22 06:31 UTC, merged